### ISSUE TITLE
Can't connect to XDebug in PHP 7.4 container

### ISSUE THREAD

**Issue by dominikmiskovec** [pvtl/docker-dev#10]
Hi!

I would like to solve an issue about xdebug and phpstorm on container php74-fpm. I tried step by step to allow xdebug in container, restart it and connect through the manual on official phpstorm documentation.

<img width="1073" alt="Snímek obrazovky 2020-12-15 v 10 05 31" src="https://user-images.githubusercontent.com/75794111/102194013-12cb8180-3ebd-11eb-804e-039d95794eea.png">

As you can see the debugger says **Not installed**.  I have tried to add ports in docker-compose.yml and it still won't work.
<img width="756" alt="Snímek obrazovky 2020-12-15 v 10 07 11" src="https://user-images.githubusercontent.com/75794111/102194196-4f977880-3ebd-11eb-9dcb-6eaa3a5779e2.png">

There is a bash of the PHP74-fpm container where it says that Xdebug 3.0.1 is activated.

**Comment by mcnamee** [comment]
Great question @dominikmiskovec 

Hey @wireblue - this sounds like it might be in your area of expertise - do you have any advice that you can share?

**Comment by wireblue** [comment]
Hi @dominikmiskovec,

I've just [committed multiple improvements](https://github.com/pvtl/docker-dev/commit/55e4d63b10f6f57fe003fa5f64cf764e864a7508) to how XDebug is setup, configured and documented. Hopefully there's something in there that will help solve your question.

I've also seen that `Debugger: Not Installed` PHPStorm issue on a fellow developer's machine. It was a while back and I don't remember all the details... we weren't able to find a solution at the time, but were able to use XDebug regardless. If you have found a solution I'd love to include it in the documentation.
