### ISSUE TITLE
Starting XDebug on Mac

### ISSUE THREAD

**Issue by freshdevelop** [pvtl/docker-dev#21]
MacBook Pro Intel CPU, os 11.3.1
Docker v. 4.2.0 (70708)

Cloned docker-dev repo
Enabled php 7.4 into the .env file
Enabled xdebug as described into the [docs](https://github.com/pvtl/docker-dev/blob/master/docs/xdebug.md)
Configured vscode to run xdebug with this launch configuration:

`{
				"name": "Listen for Xdebug",
				"type": "php",
				"request": "launch",
				"port": 9000
			},`

Created a info.php page with a variable instantiation and a phpinfo() and added a breakpoint on the first line
Started xdebug via vscode
Navigated info.php page in browser

The page renders correctly, but xdebug won't stop at the breakpoint.

Repeated the procedure with another docker-based solution, same xdebug configuration, it works (so it seems to be a container-related issue?)
Tried adding different vscode configurations (e.g. adding `"hostname": "0.0.0.0",`) without success
Tried ssh tunneling within the container and running vscode in this, it works (but it's not a really practical solution)

**Comment by wireblue** [comment]
Hey there,

Here's a few things you could try:

1. Try adding "pathMappings" to your Xdebug launch configuration in VS Code. Make sure the paths suit your environment. I realise this wasn't documented properly, so I've [added it now](https://github.com/pvtl/docker-dev/blob/master/docs/xdebug.md#vs-code).
1. I think you've already done this, but make sure you've clicked the green "Listen for Xdebug" button to enable VS Code to listen for incoming Xdebug connections (or reload it if you've recently changed the config)
1. Make sure you're sending one of the special activation keywords in your HTTP request. The Google Chrome Xdebug helper will do this for you, just make sure it's in "Debug" mode. Alternatively you can append `?XDEBUG_SESSION_START` to the URL.

Let me know how you go. It would be great to add anything we learn into the docs to help future users.
