### ISSUE TITLE
Error 404 not found

### ISSUE THREAD

**Issue by mickaelchanrion** [pvtl/docker-dev#24]
Hello!
I'm stuck on a 404 while trying to access to any project.
I followed the [installation guide](https://github.com/pvtl/docker-dev#installation-) and created a new folder `test` with a file `index.html`.

If I try to go to http://test.localhost, I get a 404 Not found

**Comment by wireblue** [comment]
Hi Mickael,

I would check that your `.env` file has been set up correct, and in particular, that the `DOCUMENTROOT` variable is pointing to the folder that contains all of your project folders.

https://github.com/pvtl/docker-dev/blob/master/.env.example#L5

For example, if your test folder is found at `/home/mickael/projects/test/`, then set `DOCUMENTROOT` to `/home/mickael/projects/`.

If you're using Ubuntu (or similar) on Windows Subsystem for Linux (WSL) then set `DOCUMENTROOT` to a folder inside Ubuntu for faster speeds.

**Comment by mickaelchanrion** [comment]
Hello,
Everything seems fine in the `.env` file. Actually, I didn't change anything from the original file (I did `cp .env.example .env`)

<img width="380" alt="image" src="https://user-images.githubusercontent.com/8982274/194827022-dee22017-9242-433b-8623-08ee6cba7882.png">

I'm working on macOS and all my projects are in a folder `~/Sites/`. I tried to put an absolute path but it's still the same.


Is there a way to list what the container sees from this folder just to make sure all the projects are listed?

**Comment by wireblue** [comment]
Ahh, great pickup! I've pushed a fix in https://github.com/pvtl/docker-dev/commit/76fc0f385eefe3f51a8d251bbba41d20b5096edf.

Just follow the [updating instructions](https://github.com/pvtl/docker-dev#updating-) and you should be good to go.
