### ISSUE TITLE
(question) Working with oAuth (Specifically google)

### ISSUE THREAD

**Issue by nullatonce** [pvtl/docker-dev#25]
Hey, I wonder how (if) you all deal with google's oAuth.
For development google accepts http://localhost or http://127.0.0.1 while my app's url goes like xxx.localhost.
Thanks for insights.

**Comment by wireblue** [comment]
Hey @nullatonce,

I've just needed to go through the same process on one of my own projects.

1. Browse the `apache/sites/localhost/` or `apache/sites/pub.localhost/` folders and choose a config that matches your needs the best (eg. PHP version, "public" folder)
2. Copy that config file and save it to `apache/sites/acme-corp.conf`.
    - NOTE: The folder location and `.conf` file extension is important, but the name itself can be whatever you want.
4. Edit your new config:
    1. Edit `ServerName` and type in the actual hostname you want to use. Eg. `ServerName acme-corp.com`
    2. Delete the `ServerAlias` lines
    3. Edit the `VirtualDocumentRoot` lines and swap `%1` for your project's folder name (eg. `acme-corp`). You should end up with a fully formed absolute folder path like `VirtualDocumentRoot /var/www/html/acme-corp/public`
6. Reload the Apache container: `docker-compose restart apache` (run this while inside the docker-dev project folder)
7. Edit your hosts file and point your domain to 127.0.0.1

**Comment by wireblue** [comment]
I've also documented this for the benefit of others:
https://github.com/pvtl/docker-dev/commit/e585fef7034da3a0dccc3718fadd4e76f7e89700
