### ISSUE TITLE
Add a PHP Analyzer like Phan (or any other)

### ISSUE THREAD

**Issue by jehanf** [pvtl/docker-dev#30]
Hey there,

I sometimes use [Phan](https://github.com/phan/phan) when I have to bump PHP version on a project, or when I get to work on some companies not-very-well maintained project, to help to not miss anything for the upcoming upgrade.

A tool like that (maybe there's a better one!) could have its place here I think.

It's just an idea, not really an issue or a request, what do you think ?

**Comment by miskovicm** [comment]
Hi,

I am not a maintainer, but static analyzers are installed per project via composer.

If they are not working correctly inside your container, maybe there are other dependencies? Like php extensions? Or did I misunderstand the question?

**Comment by jehanf** [comment]
I thought it was possible to install that globally instead of per-project, I probably misread or get things mixed up, my bad.
