### ISSUE TITLE
Add `docker builder prune` to the Update section in Readme

### ISSUE THREAD

**Issue by bennyborn** [pvtl/docker-dev#31]
Hi, we've used your stack for some years now, big thanks for that!

But each time we've updated we found ourself with some strange behaviour.
When using multiple PHP versions it happened quite often that each of the containers (php74-fpm, php81-fpm, php82-fpm) are actually built using the wrong image. The php74 was acutally running 8.1 or 8.2 and so on.

I'm not quite sure if this is an actual bug in Docker but it seems during the build it mixes up the different `Dockerfile` files.

The command `docker builder prune` was the solution for us.

Executing this before the actual build process it seems the problem is fixed.
I've built the containers multiple times without any problems.

Maybe this is something you could add to the Update section of the Readme if others are struggling as well.

**Comment by wireblue** [comment]
Hey @bennyborn, thanks for the report. That's really interesting and unusual!

Have you been following the "Updating" instructions in README.md? If not, could you post the steps you've been taking?

**Comment by bennyborn** [comment]
Hi @wireblue I did follow the instructions on updating exactly. 
Like I said I'm not even sure if this might be a bug in Docker itself but  `docker builder prune` seems to help.

**Comment by wireblue** [comment]
Thanks @bennyborn. And to confirm, are you proposing we add `docker builder prune` to the ["Updating" process](https://github.com/pvtl/docker-dev/tree/master#updating-) in README.md as a 7th step, or to the `php/src/build-n-push.sh` script, or both?

(I wasn't sure which one specifically you were running and having trouble with)

**Comment by bennyborn** [comment]
@wireblue Sorry for the confusion. I'd add `docker builder prune` in the "Updating" section in the README.md but not as step 7 but between step 2 and 3. Maybe it would be also okay between 3 and 4 but it has to be executed prior to the `docker compose build` command (in our case).

**Comment by wireblue** [comment]
Thank you again @bennyborn. While this issue doesn't affect our team, it shouldn't hurt it either. I've included your suggestion in the update steps. 👍

https://github.com/pvtl/docker-dev/commit/1d9d73e0df129018e9dfd1b13dc443aa2638c56d
