### ISSUE TITLE
You don't have permission to access / on this server.

### ISSUE THREAD

**Issue by bwx** [pvtl/docker-dev#4]
When access to the localhost got (Mac os x)
```
"Forbidden
You don't have permission to access / on this server.
```"

**Comment by mcnamee** [comment]
Hi @bwx 
Can you please supply more information:

- The URL you're accessing? (eg. `info.localhost`)
- What's in that (eg. `/info`) directory? (eg. a single index.php script with `<? phpinfo();`)
- Is docker running + all containers running (i.e. what's the output from `docker ps`?)
