### ISSUE TITLE
403 Forbidden when accessing info.localhost

### ISSUE THREAD

**Issue by slunnon12** [pvtl/docker-dev#5]
I have a forbidden 403 error when accessing apache. All sites are in Sites/info and containers are set up

**Comment by mcnamee** [comment]
Hi @slunnon12 
The good news is that docker (apache) is up and running. It'll return a 403 if it can't map to the site correctly.

Can you please confirm:

- Is the [`DOCUMENTROOT`](https://github.com/pvtl/docker-dev/blob/master/.env.example#L2) in your `.env` pointing to the correct directory?
- If your document root is say `~/Sites/`:
    - Does the following file exist? `~/Sites/info/index.php` (eg. with contents
`<?php phpinfo();`)?
        - If so, you should be able to visit [http://info.localhost](http://info.localhost) (after adding a host file record) in your browser to show a PHP info page

**Comment by slunnon12** [comment]
I can confirm that the DOCUMENTROOT is pointing to the correct place. I am on a windows machine if that helps, does the DOCUMENTROOT need to be the full path i.e. C:\docker-dev/apache...?
![notepad_AyCCqQsNsO](https://user-images.githubusercontent.com/7900386/75654091-d04ef600-5c56-11ea-9405-4242df768f12.png). this is a screenshot of my .env file

**Comment by mcnamee** [comment]
I believe that on Windows, your document root path would be something like:

- `/c/Users/Matt/Sites`

After you adjust your env file, please ensure you docker-compose stop and start the containers again

**Comment by slunnon12** [comment]
Sorted thank you all your help :-)
