### ISSUE TITLE
Support for symlinks in document root

### ISSUE THREAD

**Issue by freakimkaefig** [pvtl/docker-dev#7]
Is there a possibility to use symlinks inside the document root?

```
# /User/username/

- Projects
    + projectA
    + projectB
- Sites
    + projectA --> /User/username/Projects/projectA/public
```

Currently the symlink points to a directory that does not exist inside the docker container.

**Comment by wireblue** [comment]
Hi @freakimkaefig,

No unfortunately.

Only the document root (as set by `DOCUMENTROOT` in `.env`) is volume-mounted to the Apache and PHP containers. Everything else on your computer is not accessible.

Here's some potential solutions:

- Point `DOCUMENTROOT` to `/User/username/Sites` instead
- If you just want to load from the `public` folder, then try using this URL variation: `http://projectA.php74.pub.localhost`
- Symlinks within the `DOCUMENTROOT` folder work fine too. Eg. `/User/username/Projects/projectAPub` --> `/User/username/Projects/projectA/public`
